### ISSUE TITLE
`#[serde(skip)]` causes incorrect deserialization of enum variants

### ISSUE THREAD

**Issue by brockelmore** [bincode-org/bincode#424] opened 2021-10-25 21:07 UTC
Using `#[serde(skip)]` causes either a failure to deserialize or in some cases, misdeserialization into the wrong variant.

i.e.:
```
#[derive(Debug, Serialize, Deserialize)]
pub enum Test {
    #[serde(skip)]
    Other {
        other: u64,
    },
    InsertedMongoKeys(Vec<String>),
    MongoDeleteResult(u64),
    
}

fn main() {
    let a  = Test::InsertedMongoKeys(vec!["test".to_string()]);
    let b  = Test::MongoDeleteResult(0);
    let a_ser = bincode::serialize(&a).unwrap();
    let b_ser = bincode::serialize(&b).unwrap();
    println!("{:?} {:?}", a_ser, b_ser);
    let a_deser = bincode::deserialize::<Test>(&a_ser).unwrap();
    let b_deser = bincode::deserialize::<Test>(&b_ser).unwrap();
    println!("{:?} {:?} {:?} {:?}", a, a_deser, b, b_deser);
}
```

Will cause a crash:
```
panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid value: integer `2`, expected variant index 0 <= i < 2")'
```

It can be worked around by pushing any variant that you need to skip to the last variants in the enum, i.e.:
```
pub enum Test {
    InsertedMongoKeys(Vec<String>),
    MongoDeleteResult(u64),
    #[serde(skip)]
    Other {
        other: u64,
    },
}
```

In some cases as I have experienced, it can cause incorrect deserialization if the variant happen to be interchangeable with a surrounding variant type depending on where the `serde(skip)` is

**Comment by VictorKoenders** [comment] 2021-10-26 06:29
Unfortunately this seems to be the information we're getting from Serde. There is more information in #184 about this.

tl:dr using any `skip` attribute in serde seems to provide us with the incorrect index for the enum variant

**Comment by ghost** [comment] 2021-10-26 07:29
Yes, this is basically a duplicate of #184

**Closed as completed by ghost** 2021-10-26 07:29 UTC

**Comment by brockelmore** [comment] 2021-10-26 12:23
> Yes, this is basically a duplicate of #184 

Thanks for the replies. This is... discouraging. Can we please add some sort of documentation? Instead of a 5 year old closed issue with no resolution. This is a footgun as you can receive a valid variant in some cases.

**Comment by VictorKoenders** [comment] 2021-10-26 12:36
#326 is being kept as an open issue to indicate that documentation still needs to be added
